# Lidarr: Music manager, organizer, and PVR.
# This also installs packages for using beets internally.
# https://lidarr.audio

---
services:
  lidarr:
    image: ghcr.io/linuxserver-labs/prarr:lidarr-plugins # LSIO plugins branch.
    container_name: lidarr
    hostname: lidarr
    restart: unless-stopped
    environment:
      BEETS_DISCORD_WEBHOOK_URL: "${BEETS_DISCORD_WEBHOOK_URL}" # Discord webhook URL for Beets.
      DISCOGS_API_KEY: "${DISCOGS_API_KEY}" # Pass Discogs API key for scripts.
      DOCKER_MODS: "linuxserver/mods:universal-package-install" # Add universal-package-install support.
      GENIUS_API_KEY: "${GENIUS_API_KEY}" # Pass Genius API key for scripts.
      INSTALL_PACKAGES: "beets chromaprint ffmpeg gettext-envsubst imagemagick py3-beautifulsoup4 py3-discogs-client py3-flask py3-langdetect py3-pyacoustid py3-pylast py3-requests" # Installs required alpine packages for beets.
      LASTFM_API_KEY: "${LASTFM_API_KEY}" # Pass Last.fm API key for scripts.
      LIDARR_API_KEY: "${LIDARR_API_KEY}" # Pass Lidarr API key for scripts.
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
      UMASK: "${UMASK}"
    expose:
      - 8686/tcp # Web interface; reverse proxied internally at lidarr.${INTERNAL_DOMAIN}.
    networks:
      - external
      - gluetun
      - internal
    volumes:
      - ./beets:/config/beets:ro # Beets configuration mount.
      - ./scripts:/config/scripts:ro # Scripts mount.
      - downloads:/downloads:rw # Completed downloads mount.
      - lidarr:/config:rw # Lidarr configuration storage.
      - media-library:/library:rw # Media library mount.
    cap_drop:
      - AUDIT_WRITE
      - MKNOD
      - SETFCAP
      - SETPCAP
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    depends_on:
      arr-db:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
    healthcheck:
      interval: 1m # Run on a slower interval to avoid false negatives upon bootup due to adding packages.
      test: "curl --fail --retry 0 --silent http://127.0.0.1:8686/api/v1/system/status?apikey=${LIDARR_API_KEY} || exit 1"
    security_opt:
      - no-new-privileges:true

volumes:
  lidarr:
    name: lidarr-volume
    external: true
  downloads:
    name: downloads-bind
    driver_opts:
      device: "${DOWNLOADS_PATH}"
      o: bind
      type: none
  media-library:
    name: media-library-bind
    driver_opts:
      device: "${MEDIA_LIBRARY_PATH}"
      o: bind
      type: none
