# qBittorrent: BitTorrent client.
# VueTorrent is included at /qbittorrent/themes/vuetorrent.
# https://github.com/qbittorrent/qBittorrent/wiki

---
services:
  qbittorrent:
    image: ghcr.io/11notes/qbittorrent:5
    container_name: qbittorrent
    network_mode: service:gluetun
    read_only: true
    restart: unless-stopped
    environment:
      TZ: "${TZ}" # Sets the timezone.
    volumes:
      - downloads-incomplete:/downloads-incomplete:rw # Incomplete downloads mount.
      - downloads-permaseed:/downloads-permaseed:rw # Permaseed downloads mount.
      - downloads:/downloads:rw # Completed downloads mount.
      - qbittorrent-config:/qbittorrent/etc:rw # qBittorrent configuration storage.
      - qbittorrent-data:/qbittorrent/var:rw # qBittorrent data and database storage.
      - qbittorrent-themes:/qbittorrent/themes:rw # qBittorrent themes storage.
    cap_drop:
      - ALL
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: 4
          memory: 4GB
    security_opt:
      - no-new-privileges:true

volumes:
  qbittorrent-config:
    name: qbittorrent-config-volume
    external: true
  qbittorrent-data:
    name: qbittorrent-data-volume
    external: true
  qbittorrent-themes:
    name: qbittorrent-themes-volume
    external: true
  downloads:
    name: downloads-bind
    driver_opts:
      device: "${DOWNLOADS_PATH}"
      o: bind
      type: none
  downloads-incomplete:
    name: downloads-incomplete-bind
    driver_opts:
      device: "${DOWNLOADS_INCOMPLETE_PATH}"
      o: bind
      type: none
  downloads-permaseed:
    name: downloads-permaseed-bind
    driver_opts:
      device: "${DOWNLOADS_PERMASEED_PATH}"
      o: bind
      type: none
