# OpenCloud: Self-hosted cloud storage service.
# https://docs.opencloud.eu/docs/admin/configuration

---
services:
  opencloud:
    image: opencloudeu/opencloud-rolling:6
    command: ["-c", "opencloud init --insecure true || true; opencloud server"] # Init on first run, then run the server.
    container_name: opencloud
    entrypoint: /bin/sh # Use sh as an entrypoint for running the binary.
    hostname: opencloud
    read_only: true # Prevent writing directly to the image.
    restart: unless-stopped
    user: "${PUID}:${PGID}" # Run as non-root user.
    environment:
      FRONTEND_ARCHIVER_MAX_SIZE: "1000000000" # Maximum frontend archive size in bytes.
      IDM_ADMIN_PASSWORD: "${OPENCLOUD_ADMIN_PASSWORD}" # Sets the admin password.
      NOTIFICATIONS_SMTP_ENCRYPTION: "${SMTP_TRANSPORT_ENCRYPTION}" # SMTP server encryption method.
      NOTIFICATIONS_SMTP_HOST: "${SMTP_HOST}" # SMTP server hostname.
      NOTIFICATIONS_SMTP_INSECURE: "false" # Do not use insecure mode for SMTP.
      NOTIFICATIONS_SMTP_PASSWORD: "${SMTP_PASSWORD}" # SMTP server password.
      NOTIFICATIONS_SMTP_PORT: "${SMTP_PORT}" # SMTP server port.
      NOTIFICATIONS_SMTP_SENDER: "OpenCloud <${SMTP_SENDER}>" # SMTP server sender.
      NOTIFICATIONS_SMTP_USERNAME: "${SMTP_USERNAME}" # SMTP server username.
      OC_INSECURE: "false" # Disable insecure mode.
      OC_LOG_COLOR: "true" # Enables colored logging.
      OC_LOG_LEVEL: "info" # Sets the log level.
      OC_LOG_PRETTY: "true" # Enables pretty logging.
      OC_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD: "false" # Allow passwordless r/o shares.
      OC_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD: "true" # Require passwords for r/w shares.
      OC_URL: "https://${OPENCLOUD_URL}" # Sets the URL to use.
      PROXY_TLS: "false" # Do not proxy internal services.
    expose:
      - 9200/tcp # Web interface; reverse proxied at ${OPENCLOUD_URL}.
    networks:
      - external
    tmpfs:
      - "/tmp:uid=${PUID},gid=${PGID}" # Required for read-only image.
    volumes:
      - /etc/localtime:/etc/localtime:ro # Sets the timezone.
      - opencloud-config:/etc/opencloud:rw # OpenCloud configuration, stored in volume.
      - opencloud-metadata:/var/lib/opencloud:rw # OpenCloud metadata, stored in volume.
      - opencloud-data:/var/lib/opencloud/storage:rw # OpenCloud user uploads; bind mount.
    cap_drop:
      - ALL # Drop all unnecessary privileges.
    deploy:
      resources:
        limits:
          cpus: 4 # Allow using up to 4 CPU cores.
          memory: 4G # Allow using up to 4GB of RAM.
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://127.0.0.1:9200 || exit 1"
    security_opt:
      - no-new-privileges:true # Prevent privilege escalation.

networks:
  external:
    external: true
    name: external-network

volumes:
  opencloud-config:
    name: opencloud-config-volume
    external: true
  opencloud-metadata:
    name: opencloud-metadata-volume
    external: true
  opencloud-data:
    name: opencloud-data-bind
    driver_opts:
      device: "${OPENCLOUD_UPLOADS_PATH}"
      o: bind
      type: none
