# This is just a backup of my fstab entries for fstab.

# Bulk storage mounts
/dev/mapper/storage01 /mnt/storage01 ext4 defaults,nofail,x-systemd.device-timeout=90s 0 2
/dev/mapper/storage02 /mnt/storage02 ext4 defaults,nofail,x-systemd.device-timeout=90s 0 2
/dev/mapper/storage03 /mnt/storage03 ext4 defaults,nofail,x-systemd.device-timeout=90s 0 2

# Storage parity mount
/dev/mapper/storage-parity01 /mnt/storage-parity01 ext4 defaults,nofail,x-systemd.device-timeout=90s 0 2

# FuseFS mount
/mnt/storage01:/mnt/storage02:/mnt/storage03 /storage fuse.mergerfs allow_other,use_ino,cache.files=off,dropcache>
