parity /mnt/storage-parity01/snapraid.parity

content /var/snapraid.content
content /mnt/storage01/snapraid.content
content /mnt/storage02/snapraid.content

data d1 /mnt/storage01/
data d2 /mnt/storage02/
data d3 /mnt/storage03/

exclude /lost+found/
exclude /tmp/
