general:
  debug: false
  instance_name: "search@marinet"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: "duckduckgo"
  autocomplete_min: 4
  favicon_resolver: "duckduckgo"
  default_lang: "en"
  doi_resolver: "doi.org"
  formats:
    - html

engines:
  - name: google
    engine: google
    disabled: false
  - name: startpage
    engine: startpage
    shortcut: sp
    disabled: false
  - name: brave
    engine: brave
    shortcut: br
    disabled: false
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false
  - name: google images
    engine: google_images
    disabled: false
  - name: brave images
    engine: brave_images
    shortcut: bi
    disabled: false
  - name: google videos
    engine: google_videos
    disabled: false
  - name: google map
    engine: google_map
    disabled: false

server:
  bind_address: "0.0.0.0"
  port: 8080
  public_instance: true
  image_proxy: true

ui:
  query_in_title: false
  default_theme: simple
  center_alignment: false
  default_locale: "en"
  theme_args:
    simple_style: auto
  search_on_category_select: true
  hotkeys: default
  url_formatting: pretty
