devices:
  - device: /dev/sda
    smartctl_args: -d scsi

  - device: /dev/sdc
    smartctl_args: -d sat -xv 188,raw16 -n standby
  - device: /dev/sdd
    smartctl_args: -d sat -xv 188,raw16 -n standby
  - device: /dev/sde
    smartctl_args: -d sat -xv 188,raw16 -n standby
  - device: /dev/sdf
    smartctl_args: -d sat -xv 188,raw16 -n standby

  - device: /dev/nvme0n1
    type: nvme
  - device: /dev/nvme1n1
    type: nvme
