services:
  ###########################################################################
  # Scrutiny: Drive SMART monitoring - https://github.com/AnalogJ/scrutiny  #
  ###########################################################################

  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny
    restart: unless-stopped
    environment:
      COLLECTOR_COMMANDS_METRICS_INFO_ARGS: "-xv 188,raw16 --info --json -n standby"
      COLLECTOR_COMMANDS_METRICS_SCAN_ARGS: "-xv 188,raw16 --scan --json -n standby"
      COLLECTOR_COMMANDS_METRICS_SMART_ARGS: "-xv 188,raw16 --xall --json -n standby"
      COLLECTOR_CRON_SCHEDULE: "0 6 * * *"
      SCRUTINY_WEB_INFLUXDB_INIT_PASSWORD: ${SCRUTINY_INFLUXDB_PASSWORD}
      SCRUTINY_WEB_INFLUXDB_INIT_USERNAME: "admin"
      SCRUTINY_WEB_INFLUXDB_TOKEN: "${SCRUTINY_INFLUXDB_TOKEN}"
      TZ: ${TZ}
    expose:
      - 8080/tcp
    networks:
      - caddy
    volumes:
      - ./drivedb.h:/usr/share/smartmontools/drivedb.h # https://github.com/AnalogJ/scrutiny/issues/522#issuecomment-2807689281
      - ./drivedb.h:/var/lib/smartmontools/drivedb/drivedb.h # https://github.com/AnalogJ/scrutiny/issues/522#issuecomment-2807689281
      - /run/udev:/run/udev:ro
      - scrutiny-config:/opt/scrutiny/config
      - scrutiny-db:/opt/scrutiny/influxdb
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1024M
    devices:
      - /dev/nvme0n1
      - /dev/nvme1n1
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
      - /dev/sde
      - /dev/sdf
    healthcheck:
      test: "curl -f http://127.0.0.1:8080/web/dashboard || exit 1"
    security_opt:
      - no-new-privileges:true

networks:
  caddy:
    external: true
    name: caddy-network

volumes:
  scrutiny-config:
    name: scrutiny-config-volume
    external: true
  scrutiny-db:
    name: scrutiny-db-volume
    external: true
