# qui: Alternative web interface for qBittorrent.
# https://github.com/autobrr/qui

---
services:
  qui:
    image: ghcr.io/autobrr/qui:v1.15
    container_name: qui
    hostname: qui
    read_only: true # Prevent writing directly to the image.
    restart: unless-stopped
    user: "${PUID}:${PGID}" # Run as non-root user.
    environment:
      TZ: "${TZ}" # Sets the timezone.
    networks:
      - external
      - gluetun
      - internal
    volumes:
      - qui:/config:rw # qui configuration storage.
    cap_drop:
      - ALL # Drop all unnecessary privileges.
    depends_on:
      qbittorrent:
        condition: service_healthy # Require qBittorrent to be healthy before starting.
        restart: true # Restart when qBittorrent restarts.
    deploy:
      resources:
        limits:
          cpus: 1 # Allow using up to 1 CPU core.
          memory: 512M # Allow using up to 512MB of RAM.
    security_opt:
      - no-new-privileges:true # Prevent privilege escalation.

networks:
  external:
    name: external-network
    external: true
  gluetun:
    name: gluetun-network
    external: true
  internal:
    name: internal-network
    external: true

volumes:
  qui:
    name: qui-volume
    external: true
