# qui: qBittorrent management interface.
# https://github.com/autobrr/qui

---
services:
  qui:
    image: ghcr.io/autobrr/qui:v1.17
    container_name: qui
    hostname: qui
    read_only: true
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    environment:
      TZ: "${TZ}"
    networks:
      - external
      - gluetun
      - internal
    volumes:
      - qui:/config:rw # qui configuration storage.
    cap_drop:
      - ALL
    depends_on:
      qbittorrent:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 512M
    security_opt:
      - no-new-privileges:true

networks:
  external:
    name: external-network
    external: true
  gluetun:
    name: gluetun-network
    external: true
  internal:
    name: internal-network
    external: true

volumes:
  qui:
    name: qui-volume
    external: true
