bots:
  - name: trusted-ip-whitelist
    action: "ALLOW"
    priority: 200
    description: "Allow Trusted IP Ranges"
    remote_addresses:
      - "10.0.0.1/8"
      - "100.64.0.0/10" # Tailscale IPV4 range.
      - "127.0.0.1/8"
      - "172.17.0.0/16" # Default Docker bridge network.
      - "172.19.1.0/24" # External Docker bridge network IPV4 range.
      - "172.19.2.0/24" # Internal Docker bridge network IPV4 range.
      - "172.19.3.0/24" # Gluetun Docker bridge network IPV4 range.
      - "fd7a:115c:a1e0::/48" # Tailscale IPV6 range.
      - "fdad:21b2:bca9:1::/64" # External Docker bridge network IPV6 range.
      - "fdad:21b2:bca9:2::/64" # Internal Docker bridge network IPV4 range.
      - "fdad:21b2:bca9:3::/64" # Gluetun Docker bridge network IPV4 range.

  # Chhoto URL.
  - name: chhoto-api-bypass
    path_regex: "^/api/.*$" # Path regex is the implicit match field here
    action: "ALLOW"
    priority: 100
    description: "Allow Chhoto API calls"

  # Homarr
  - name: homarr-api-bypass
    path_regex: "^/api/.*$"
    action: "ALLOW"
    priority: 100
    description: "Allow Homarr API Calls"

  # Jellyfin.
  - name: jellyfin-ws-bypass
    path_regex: "^/sock.*$"
    action: "ALLOW"
    priority: 100
    description: "Allow Jellyfin App/Live Sync WebSockets"
  - name: jellyfin-api-bypass
    path_regex: "^/api/.*$"
    action: "ALLOW"
    priority: 100
    description: "Allow Jellyfin API"

  # OpenCloud.
  - name: opencloud-api-bypass
    path_regex: "^/api/.*$"
    action: "ALLOW"
    priority: 100
    description: "Allow OpenCloud API Calls"
  - name: opencloud-dav-bypass
    path_regex: "^/dav/.*$"
    action: "ALLOW"
    priority: 100
    description: "Allow OpenCloud WebDAV/CalDAV"

  # Piwigo.
  - name: piwigo-ws-bypass
    path_regex: "^/ws.php$"
    action: "ALLOW"
    priority: 100
    description: "Allow Piwigo Web Services API"

  # Seerr.
  - name: seerr-api-bypass
    path_regex: "^/api/.*$"
    action: "ALLOW"
    priority: 100
    description: "Allow Seerr API Calls"
  - name: seerr-ws-bypass
    path_regex: "^/socket.io/.*$"
    action: "ALLOW"
    priority: 100
    description: "Allow Seerr WebSockets"

  # The Lounge.
  - name: thelounge-ws-bypass
    path_regex: "^/socket.io/.*$"
    action: "ALLOW"
    priority: 100
    description: "Allow The Lounge Socket.io"

  # Vaultwarden.
  - name: vaultwarden-ws-bypass
    path_regex: "^/notifications/hub.*$"
    action: "ALLOW"
    priority: 100
    description: "Allow Vaultwarden Live Sync WebSockets"

  # Gatus.
  - name: gatus-health-bypass
    path_regex: "^/health$"
    action: "ALLOW"
    priority: 100
    description: "Allow Gatus /health endpoint"
  - name: gatus-api-bypass
    path_regex: "^/api/.*$"
    action: "ALLOW"
    priority: 100
    description: "Allow Gatus API calls"
