# Autobrr: Download automation tool and ratio manager.
# https://autobrr.com/introduction

---
services:
  autobrr:
    image: ghcr.io/s0up4200/autobrr-distroless:v1.79
    container_name: autobrr
    read_only: true
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    environment:
      AUTOBRR__DATABASE_TYPE: "postgres"
      AUTOBRR__POSTGRES_DATABASE: "autobrr"
      AUTOBRR__POSTGRES_HOST: "media-db"
      AUTOBRR__POSTGRES_PASS: "${MEDIA_DB_PASSWORD}"
      AUTOBRR__POSTGRES_PORT: "5432"
      AUTOBRR__POSTGRES_USER: "postgres"
    networks:
      - external
      - gluetun
      - internal
    tmpfs:
      - "/tmp:uid=${PUID},gid=${PGID}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - autobrr:/config:rw
    cap_drop:
      - ALL
    depends_on:
      gluetun:
        condition: service_healthy
        restart: true
      media-db:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
    security_opt:
      - no-new-privileges:true

networks:
  external:
    external: true
    name: external-network
  gluetun:
    external: true
    name: gluetun-network
  internal:
    external: true
    name: internal-network

volumes:
  autobrr:
    name: autobrr-volume
    external: true
