plugins: discogs embedart fetchart lastgenre lyrics scrub zero
library: /config/musiclibrary.blb # Save the beets library to the volume.
threaded: yes # Enable multithreading.

# Matching/metadata options.
match:
  preferred:
    original_year: yes # Match releases to their original year instead of reissue.
original_date: yes # In Utero (1993) instead of In Utero (30th Anniversary) (2023).
per_disc_numbering: yes # Enable per-disk numbering.

# Import configuration.
import:
  copy: no # Do not copy files.
  hardlink: no # Do not hardlink files.
  incremental: no # Allow re-running later.
  log: /config/beets-logs/beet.log # Save log files.
  move: no # Do not move files.
  quiet_fallback: skip # Skip files that cannot automatically be matched.
  resume: no # Do not resume if exited.
  timid: no # Do not run timidly; automatically tag matching releases.
  write: yes # Write changes to the files.

# Album art configuration.
art_filename: cover
embedart:
  auto: yes # Automatically embed album art.
  maxwidth: 1200 # Save album art up to 1200x1200.
  remove_art_file: no # Do not remove the album art file.
fetchart:
  cover_names: cover front back art album # Names to store files as.
  auto: yes # Automatically fetch album art.
  enforce_ratio: yes # Require album art to be a 1:1 ratio.
  minwidth: 500 # Require album art to be 500x500 or larger.
  maxwidth: 1200 # Max width of 1200.
  sources: [coverart, itunes, filesystem] # Sources to enable.

# Discogs configuration.
discogs:
  index_tracks: yes # Fetch track data from Discogs as a backup.
  user_token: "${DISCOGS_API_KEY}"

# Last.fm genre configuration.
lastgenre:
  auto: yes # Automatically fetch genre data from Last.fm.
  canonical: yes # Use a canonical whitelisted map.
  count: 5 # Fetch the top 5 most popular genres.
  force: yes # Force setting the genre tags.
  keep_existing: no # Do not keep pre-existing genre tags.
  prefer_specific: true # Prefer setting specific tags (i.e Grunge instead of Rock) as the primary tag.
  source: album # Source the genre from the album.

# Lyrics configuration.
lyrics:
  auto: yes # Automatically fetch lyrics.
  fallback: "" # Wipe existing lyrics if none are found.
  genius_api_key: "${GENIUS_API_KEY}"
  sources: [lrclib, genius] # Sources to enable.
  synced: yes # Prefer synced lyrics.

# Tag scrubbing configuration.
scrub:
  auto: yes # Automatically scrub existing tags.
zero:
  fields: comments encoder # Tags to remove.
  update_database: true # Update the database when finished.
