---
# Plugins to enable.
# chroma: Audio fingerprinting for automatic matches.
# discogs: Discogs API support for releases not on MusicBrainz.
# embedart: Embedded art support.
# fetchart: Fetch remote album art.
# ftintitle: Move featured artists to track titles instead of the artist tag.
# lastgenre: Import genres from Last.fm.
# lyrics: Fetch and embed remote lyrics.
# scrub: Tag scrubber for removing old/useless tags.
# zero: Further tag scrubbing for tags not supported by scrub.
plugins: chroma discogs embedart fetchart ftintitle lastgenre lyrics scrub zero

# Beets configuration.
library: /config/musiclibrary.blb # Save the beets database.
threaded: yes # Enable multithreading.

# Import configuration.
import:
  copy: no # Don't copy files when complete.
  hardlink: no # Don't create hardlinks when complete.
  incremental: no # Don't run incrementally. Allows re-writes.
  log: /config/beet.log # Save log files inside of the container.
  move: no # Don't move files when complete.
  quiet_fallback: skip # Skip fallbacks when running in quiet mode.
  resume: no # Don't resume upon crashing.
  timid: no # Don't use timid mode.
  write: yes # Write the changes in place.

# Album art configuration.
art_filename: cover # Save album art as cover.jpeg.
embedart:
  auto: yes # Automatically embed album art.
  maxwidth: 1500 # Only embed images up to 1500x1500.
  remove_art_file: no # Do not remove cover.jpeg.
fetchart:
  auto: yes # Automatically download album art.
  enforce_ratio: yes # Enforce the ratio.
  minwidth: 1000 # Require 1000x1000 art at the minimum.
  lastfm_key: "${LASTFM_API_KEY}" # Connect script will inject the real token here.
  sources: [filesystem, coverart, itunes, amazon] # Sources to use.

# Discogs configuration.
discogs:
  index_tracks: yes # Index tracks.
  user_token: "${DISCOGS_API_KEY}" # Connect script will inject the real token here.

# Adds featured artists to the title instead of the tags.
ftintitle:
  auto: yes # Automatically move feat. to the title.
  drop: no # Do not remove it entirely.
  format: "(feat. {0})" # (feat. Meowing On The Internet)

# Last.fm genre configuration.
lastgenre:
  auto: yes # Automatically fetch the genre from Last.fm.
  canonical: yes # Uses a built-in tree to fix weird capitalization/spelling.
  count: 3 # Grabs up to 3 genres.
  force: yes # Overwrite existing genres.
  min_weight: 5 # Dropping this from the default 10 allows catching more niche genres.
  prefer_specific: yes # Prefer specific genres over generic ones.
  separator: ";" # Semicolons are the standard for genre seperation.
  source: album # Use the album as the source for genres.

# Lyrics configuration.
lyrics:
  auto: yes # Automatically download lyrics.
  fallback: "" # Do not include fallback lyrics.
  genius_api_key: "${GENIUS_API_KEY}" # Connect script will inject the real token here.
  sources: [lrclib, musixmatch, tekstowo, genius] # Sources to use.
  synced: yes # Enable synced lyrics.

# Match configuration.
match:
  preferred:
    countries: ["US", "GB", "XW"] # XW is MusicBrainz code for Worldwide
    media: ["Digital Media", "CD", "Vinyl"]

# Metadata configuration.
original_date: yes # Use the original date, not the release date (i.e 1993 i)
per_disc_numbering: yes # Enable per-disc numbering.

# Scrubbing configuration. Also enables Zero for scrubbing misc. tags.
scrub:
  auto: yes # Scrub existing standardized tags.
zero:
  fields: comments encoder images # Scrub useless tags.
  update_database: true # Update the database when complete.
