services:
  ###########################################################################
  # Profilarr: Config management for 'ARR apps - https://dictionarry.dev/   #
  ###########################################################################

  profilarr:
    image: santiagosayshey/profilarr:v1.1.3
    container_name: profilarr
    hostname: profilarr
    restart: unless-stopped
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
      UMASK: "${UMASK}"
    expose:
      - 6868/tcp
    networks:
      - caddy
      - gluetun
    volumes:
      - profilarr:/config
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 256M
        reservations:
          cpus: 0.125
          memory: 128M
    security_opt:
      - no-new-privileges:true

networks:
  caddy:
    external: true
    name: caddy-network
  gluetun:
    driver: bridge
    external: true
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
    name: gluetun-network

volumes:
  profilarr:
    external: true
    name: profilarr-volume
