services:
  ###########################################################################
  # Profilarr: Config management for 'ARR apps - https://dictionarry.dev/   #
  ###########################################################################

  profilarr:
    image: santiagosayshey/profilarr:v1.1.3
    container_name: profilarr
    env_file: ../../.env
    hostname: profilarr
    restart: unless-stopped
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
      UMASK: "${UMASK}"
    expose:
      - 6868/tcp
    networks:
      - caddy
      - gluetun
    volumes:
      - profilarr:/config
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: 256M
        reservations:
          cpus: "0.05"
          memory: 128M
    security_opt:
      - no-new-privileges:true
