---
services:
  ###########################################################################
  # Profilarr: Sonarr/Radarr profile and custom format manager.             #
  ###########################################################################

  profilarr:
    image: santiagosayshey/profilarr:beta
    container_name: profilarr
    env_file: ../../.env
    hostname: profilarr
    read_only: true # Prevent writing directly to the image.
    restart: unless-stopped
    environment:
      TZ: "${TZ}" # Sets the timezone.
      PGID: "${PGID}" # Group ID to run as.
      PUID: "${PUID}" # User ID to run as.
      UMASK: "${UMASK}" # Umask to apply to newly created files.
    expose:
      - 6868/tcp # Web interface reverse proxied internally at profilarr.${INTERNAL_DOMAIN}.
    networks:
      - external
    tmpfs:
      - "/tmp:uid=${PUID},gid=${PGID}" # Required for read_only images.
      - "/home/appuser:uid=${PUID},gid=${PGID},exec" # Required for Profilarr.
    volumes:
      - profilarr:/config # Configuration and data.
    cap_drop:
      - AUDIT_WRITE
      - MKNOD
      - SETFCAP
      - SETPCAP
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    deploy:
      resources:
        limits:
          cpus: 0.5 # Allow up to 0.5 vCPUs.
          memory: 512M # Allow up to 512MB of RAM.
    healthcheck:
      test: "curl -f http://127.0.0.1:6868 || exit 1"
    security_opt:
      - no-new-privileges:true # Prevent privilege escalation.

networks:
  external:
    external: true
    name: external-network

volumes:
  profilarr:
    external: true
    name: profilarr-volume
