# Immich: Self-hosted photo manager and organizer.
# https://immich.app

---
# Default container options.
x-defaults: &defaults
  restart: unless-stopped
  read_only: true # Prevent writing directly to the image.
  cap_drop:
    - ALL # Drop all unnecessary privileges.
  security_opt:
    - no-new-privileges:true # Prevent privilege escalation.

services:
  immich:
    <<: *defaults
    image: ghcr.io/immich-app/immich-server:v2.5.6
    container_name: immich
    user: "${PUID}:${PGID}" # Run as non-root user.
    environment:
      REDIS_PASSWORD: "${IMMICH_REDIS_PASSWORD}" # Redis password to authenticate with.
      DB_URL: "postgresql://postgres:${IMMICH_DB_PASSWORD}@immich-db:5432/immich" # Connect to PostgreSQL.
      REDIS_HOSTNAME: "immich-cache" # Connect to immich-cache.
      MACHINE_LEARNING_HOST: "immich-ml" # Connect to immich-ml.
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128:rw # Required for transcoding; renderD128 is usually GPU0.
    expose:
      - 2283/tcp # Web interface; reverse proxied at ${IMMICH_URL}.
    networks:
      - external
      - internal
    tmpfs:
      - "/run:uid=${PUID},gid=${PGID}" # Required for read-only image.
      - "/tmp:uid=${PUID},gid=${PGID}" # Required for read-only image.
      - "/usr/src/app/.npm:uid=${PUID},gid=${PGID}" # Required for read-only image; installation.
      - "/usr/src/app/.config:uid=${PUID},gid=${PGID}" # Required for read-only image; cache.
    volumes:
      - /etc/localtime:/etc/localtime:ro # Sets the timezone.
      - immich-data:/data:rw # Immich storage mount.
    depends_on:
      immich-cache:
        condition: service_healthy # Require immich-cache to be healthy before starting.
        restart: true # Restart when immich-cache is restarted.
      immich-db:
        condition: service_healthy # Require immich-db to be healthy before starting.
        restart: true # Restart when immich-db is restarted.
      immich-ml:
        condition: service_healthy # Require immich-ml to be healthy before starting.
        restart: true # Restart when immich-ml is restarted.
    deploy:
      resources:
        limits:
          cpus: 4 # Allow using up to 4 CPU cores.
          memory: 4G # Allow using up to 4GB of RAM.
    group_add:
      - "${RENDER_PGID}" # Required for video transcoding.

  immich-cache:
    <<: *defaults
    image: ghcr.io/11notes/redis:8
    container_name: immich-cache
    environment:
      REDIS_PASSWORD: "${IMMICH_REDIS_PASSWORD}" # Sets the redis password.
      TZ: "${TZ}" # Sets the timezone.
    networks:
      - internal
    tmpfs:
      - "/tmp:uid=1000,gid=1000" # Required for read-only image.
    volumes:
      - immich-cache-config:/redis/etc:rw # Redis cache config storage.
      - immich-cache-data:/redis/var:rw # Redis cache storage.
    deploy:
      resources:
        limits:
          cpus: 1 # Allow using up to 1 CPU core.
          memory: 1G # Allow using up to 1GB of RAM.

  immich-db:
    <<: *defaults
    image: ghcr.io/immich-app/postgres:18-vectorchord0.5.3
    container_name: immich-db
    shm_size: 512MB # Increases the shared memory size.
    environment:
      DB_STORAGE_TYPE: "${IMMICH_DB_STORAGE_TYPE}" # HDD or SSD; enables optimizations.
      POSTGRES_DB: "immich" # Use the immich database.
      POSTGRES_INITDB_ARGS: "--data-checksums" # Enable checksums.
      POSTGRES_PASSWORD: "${IMMICH_DB_PASSWORD}" # Sets the PostgreSQL password.
      POSTGRES_USER: "postgres" # Use the immich user.
      TZ: "${TZ}" # Sets the timezone.
    networks:
      - internal
    tmpfs:
      - "/etc/postgresql:exec" # Required for read-only image; psql.
      - "/run" # Required for read-only image.
      - "/tmp" # Required for read-only image.
    volumes:
      - immich-db:/var/lib/postgresql:rw # PostgreSQL database storage.
    cap_drop: # Drop all unnecessary privileges.
      - AUDIT_WRITE
      - MKNOD
      - SETFCAP
      - SETPCAP
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    deploy:
      resources:
        limits:
          cpus: 1 # Allow using up to 1 CPU core.
          memory: 2G # Allow using up to 2GB of RAM.

  immich-ml:
    <<: *defaults
    image: ghcr.io/immich-app/immich-machine-learning:v2.5.6-openvino
    container_name: immich-machine-learning
    hostname: immich-ml
    user: "${PUID}:${PGID}" # Run as non-root user.
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128:rw # Required for ML.
    environment:
      MACHINE_LEARNING_MAX_BATCH_SIZE__FACIAL_RECOGNITION: 1 # Use FR #1.
      MACHINE_LEARNING_WORKER_TIMEOUT: 300 # Timeout after 300s.
      MACHINE_LEARNING_WORKERS: 2 # Use 2 workers.
      MPLCONFIGDIR: /tmp/matplotlib # Use a writable tmpfs for mpl.
    expose:
      - 3003/tcp # Internal API port for the Immich server.
    networks:
      - internal
    tmpfs:
      - "/tmp:uid=${PUID},gid=${PGID}" # Required for read-only image.
      - "/run:uid=${PUID},gid=${PGID}" # Required for read-only image.
      - "/usr/src/app/.config:uid=${PUID},gid=${PGID}" # Required for read-only image; cache.
    volumes:
      - /etc/localtime:/etc/localtime:ro # Sets the timezone.
      - immich-model-cache:/cache:rw # Persistent storage for downloaded ML models.
    group_add:
      - "${RENDER_PGID}" # Grants permission to use the GPU via the render group.
    deploy:
      resources:
        limits:
          cpus: 4 # Allow using up to 4 CPU cores.
          memory: 8G # Allow using up to 8GB of RAM.

networks:
  external:
    external: true
    name: external-network
  internal:
    external: true
    name: internal-network

volumes:
  immich-cache-config:
    name: immich-cache-config-volume
    external: true
  immich-cache-data:
    name: immich-cache-data-volume
    external: true
  immich-model-cache:
    name: immich-model-cache-volume
    external: true
  immich-db:
    name: immich-db-volume
    external: true
  immich-data:
    name: immich-data-bind
    driver_opts:
      device: "${IMMICH_UPLOADS_PATH}"
      o: bind
      type: none
