# Dispatcharr: IPTV stream manager.
---
services:
  dispatcharr:
    image: ghcr.io/dispatcharr/dispatcharr:0.22.1
    container_name: dispatcharr
    restart: unless-stopped
    hostname: dispatcharr
    devices:
      - /dev/dri:/dev/dri:rw # For GPU acceleration.
    environment:
      DISPATCHARR_ENV: "aio" # Use AIO mode.
      REDIS_HOST: "localhost" # Connect to localhost redis.
      CELERY_BROKER_URL: "redis://localhost:6379/0" # Connect to redis.
      DISPATCHARR_LOG_LEVEL: "info" # Sets the log level.
    expose:
      - 9191/tcp # Web interface reverse proxied internally at dispatcharr.${INTERNAL_DOMAIN}.
    networks:
      - external
      - internal
    volumes:
      - dispatcharr:/data:rw # Dispatcharr data.
      - /etc/localtime:/etc/localtime:ro # Sets the timezone.
    cap_drop:
      - AUDIT_WRITE
      - MKNOD
      - SETFCAP
      - SETPCAP
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    security_opt:
      - no-new-privileges:true # Prevent privilege escalation.
    deploy:
      resources:
        limits:
          cpus: 2 # Allow using up to 2 CPU cores.
          memory: 2G # Allow using up to 2GB of RAM.
    group_add:
      - "${RENDER_PGID}" # Required for transcoding.

networks:
  internal:
    external: true
    name: internal-network
  external:
    external: true
    name: external-network

volumes:
  dispatcharr:
    external: true
    name: dispatcharr-volume
