# Dispatcharr: IPTV stream and playlist manager.
# https://github.com/dispatcharr/dispatcharr

---
services:
  dispatcharr:
    image: ghcr.io/dispatcharr/dispatcharr:0.23.0
    container_name: dispatcharr
    restart: unless-stopped
    hostname: dispatcharr
    devices:
      - /dev/dri:/dev/dri:rw # Required for transcoding.
    environment:
      CELERY_BROKER_URL: "redis://localhost:6379/0" # Connect to redis.
      DISPATCHARR_ENV: "aio" # Use AIO mode with bundled services.
      DISPATCHARR_LOG_LEVEL: "info"
      PGID: "${PGID}"
      PUID: "${PUID}"
      REDIS_HOST: "localhost" # Connect to the local redis.
      TZ: "${TZ}"
      UMASK: "${UMASK}"
    expose:
      - 9191/tcp # Web interface reverse proxied internally at dispatcharr.${INTERNAL_DOMAIN}.
    networks:
      - external
      - internal
    volumes:
      - dispatcharr:/data:rw # Dispatcharr configuration and data.
      - /etc/localtime:/etc/localtime:ro # Sets the timezone.
    cap_drop:
      - AUDIT_WRITE
      - MKNOD
      - SETFCAP
      - SETPCAP
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
    group_add:
      - "${RENDER_PGID}" # Required for transcoding.
    security_opt:
      - no-new-privileges:true # Prevent privilege escalation.

networks:
  external:
    external: true
    name: external-network
  internal:
    external: true
    name: internal-network

volumes:
  dispatcharr:
    external: true
    name: dispatcharr-volume
