# The Lounge: Web-based IRC client and bouncer.
# https://github.com/thelounge/thelounge-docker

---
services:
  thelounge:
    image: ghcr.io/thelounge/thelounge:4
    container_name: thelounge
    hostname: thelounge
    read_only: true # Prevent writing directly to the image.
    restart: unless-stopped
    user: "${PUID}:${PGID}" # Run as non-root user.
    expose:
      - 9000/tcp # Web interface; reverse proxied at thelounge.${INTERNAL_DOMAIN}.
    networks:
      - external
    tmpfs:
      - "/tmp:uid=${PUID},gid=${PGID}" # Required for read-only image.
    volumes:
      - /etc/localtime:/etc/localtime:ro # Sets the timezone.
      - thelounge:/var/opt/thelounge:rw # The Lounge configuration and data.
    cap_drop:
      - ALL # Drop all unnecessary privileges.
    deploy:
      resources:
        limits:
          cpus: 1 # Allow using up to 1 CPU core.
          memory: 512M # Allow using up to 512MB of RAM.
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://127.0.0.1:9000 || exit 1"
    security_opt:
      - no-new-privileges:true # Prevent privilege escalation.

networks:
  external:
    external: true
    name: external-network

volumes:
  thelounge:
    external: true
    name: thelounge-volume
