---
x-defaults-env: &defaults-env
  TZ: "${TZ}" # Sets the timezone.
  PGID: "${PGID}" # Group ID to run as.
  PUID: "${PUID}" # User ID to run as.
  UMASK: "${UMASK}" # Umask to apply to newly created files.

x-defaults: &defaults
  env_file: ../../.env
  restart: unless-stopped
  environment: *defaults-env
  cap_drop:
    - AUDIT_WRITE
    - MKNOD
    - SETFCAP
    - SETPCAP
    - SYS_ADMIN
    - SYS_CHROOT
    - SYS_PTRACE
  security_opt:
    - no-new-privileges:true # Prevent privilege escalation.

services:
  ###########################################################################
  # Piwigo: Self-hosted photo management - https://piwigo.org/              #
  ###########################################################################

  piwigo:
    <<: *defaults
    image: lscr.io/linuxserver/piwigo:latest
    container_name: piwigo
    hostname: piwigo
    expose:
      - 80/tcp # Web interface reverse proxied externally at ${PIWIGO_URL}.
    networks:
      - external
      - internal
    volumes:
      - piwigo:/config # Configuration and user data.
      - piwigo-data:/gallery # Photo storage destination.
    deploy:
      resources:
        limits:
          cpus: 2 # Allow up to 2 vCPUs.
          memory: 4G # Allow up to 4G of RAM.
    depends_on:
      piwigo-db:
        condition: service_healthy # Require piwigo-db to be healthy before connecting.
        restart: true # Restart when piwigo-db restarts.
    healthcheck:
      test: "curl -f http://127.0.0.1:80 || exit 1"

  piwigo-db:
    <<: *defaults
    image: lscr.io/linuxserver/mariadb:latest
    container_name: piwigo-db
    hostname: piwigo-db
    environment:
      <<: *defaults-env
      MYSQL_DATABASE: "piwigo" # Create the piwigo database.
      MYSQL_PASSWORD: "${PIWIGO_DB_PASSWORD}" # Sets the DB password.
      MYSQL_ROOT_PASSWORD: "${PIWIGO_DB_ROOT_PASSWORD}" # Sets the DB root password.
      MYSQL_USER: "piwigo" # Create the piwigo user.
    networks:
      internal:
        ipv4_address: 172.19.2.43 # Static IPV4 from the internal subnet
        ipv6_address: fdad:21b2:bca9:1::43 # Static IPV6 equivalent
    volumes:
      - piwigo-db:/config # Piwigo database volume.
    deploy:
      resources:
        limits:
          cpus: 1 # Allow up to 1 vCPUs.
          memory: 2G # Allow up to 2G of RAM.
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1"]

  ###########################################################################
  # Anubis: Anti-bot/scraper tool - https://anubis.techaro.lol              #
  ###########################################################################

  piwigo-anubis:
    <<: *defaults
    image: ghcr.io/techarohq/anubis:latest
    container_name: piwigo-anubis
    hostname: piwigo-anubis
    read_only: true # Prevent writing directly to the image.
    user: "${PUID}:${PGID}" # Run as non-root user.
    environment:
      BIND: ":80" # Bind to the used container port.
      ED25519_PRIVATE_KEY_HEX: "${PIWIGO_ANUBIS_KEY}" # Sets the private key.
      REDIRECT_DOMAINS: "*.${PIWIGO_URL}" # Sets allowed redirect URLs.
      SERVE_ROBOTS_TXT: "true" # Serve a default robots.txt.
      SLOG_LEVEL: "DEBUG" # Log more things.
      TARGET: "http://piwigo:80" # Target the container.
      TZ: "${TZ}" # Sets the timezone.
      WEBMASTER_EMAIL: "${ACME_EMAIL}" # Sets the webmaster email.
    networks:
      - external
    cap_drop:
      - ALL # Drop all default capabilities.
    depends_on:
      caddy:
        condition: service_healthy # Require Caddy to be healthy.
        restart: true # Restart when Caddy restarts.
      piwigo:
        condition: service_healthy # Require Piwigo to be healthy.
        restart: true # Restart when Piwigo restarts.
    deploy:
      resources:
        limits:
          cpus: 0.25 # Allow up to 0.25 vCPUs.
          memory: 64M # Allow up to 64MB of RAM.
    healthcheck:
      test: ["CMD", "anubis", "--healthcheck"]

networks:
  external:
    external: true
    name: external-network
  internal:
    external: true
    name: internal-network

volumes:
  piwigo:
    external: true
    name: piwigo-volume
  piwigo-db:
    external: true
    name: piwigo-db-volume
  piwigo-data:
    name: piwigo-data-bind
    driver_opts:
      device: "${APPDATA_PATH}/piwigo"
      o: bind
      type: none
