---
services:
  ###########################################################################
  # Cleanuparr: Automated cleanup of 'ARR apps and qBittorrent.             #
  ###########################################################################

  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:2
    container_name: cleanuparr
    env_file: ../../.env
    hostname: cleanuparr
    restart: unless-stopped
    environment:
      PGID: "${PGID}" # Group ID to run as.
      PORT: "11011" # Sets the port.
      PUID: "${PUID}" # User ID to run as.
      TZ: "${TZ}" # Sets the timezone.
      UMASK: "${UMASK}" # Umask to apply to newly created files.
    expose:
      - 11011/tcp # Web interface reverse proxied internally at cleanuparr.${INTERNAL_DOMAIN}.
    networks:
      external:
      gluetun:
        ipv4_address: 172.19.3.24
        ipv6_address: "${DOCKER_IPV6_ULA_BASE}:3::24"
    volumes:
      - cleanuparr:/config # Configuration and data.
    cap_drop:
      - AUDIT_WRITE
      - MKNOD
      - SETFCAP
      - SETPCAP
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    deploy:
      resources:
        limits:
          cpus: 0.5 # Allow up to 0.5 vCPUs.
          memory: 1G # Allow up to 1GB of RAM.
    healthcheck:
      test: "curl --fail --retry 0 --silent http://127.0.0.1:11011 || exit 1"
    security_opt:
      - no-new-privileges:true # Prevent privilege escalation.

networks:
  external:
    external: true
    name: external-network
  gluetun:
    external: true
    name: gluetun-network

volumes:
  cleanuparr:
    external: true
    name: cleanuparr-volume
