services:
  ###########################################################################
  # Cleanuparr: Automatic cleanup for 'ARR apps and qBittorrent.            #
  ###########################################################################

  cleanuparr:
    image: ghcr.io/cleanuparr/cleanuparr:2.3.3
    container_name: cleanuparr
    hostname: cleanuparr
    restart: unless-stopped
    environment:
      PGID: "${PGID}"
      PUID: "${PUID}"
      TZ: "${TZ}"
      PORT: "11011"
      UMASK: "${UMASK}"
    expose:
      - 11011/tcp
    networks:
      - caddy
      - gluetun
    volumes:
      - cleanuparr:/config
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:11011/health"]
    security_opt:
      - no-new-privileges:true

networks:
  caddy:
    external: true
    name: caddy-network
  gluetun:
    driver: bridge
    external: true
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
    name: gluetun-network

volumes:
  cleanuparr:
    external: true
    name: cleanuparr-volume
