# Jellyfin: Home media server.
# https://jellyfin.org/docs/

---
services:
  jellyfin:
    image: ghcr.io/jellyfin/jellyfin:10.11
    container_name: jellyfin
    hostname: jellyfin
    read_only: true # Prevent writing directly to the image.
    restart: unless-stopped
    user: "${PUID}:${PGID}" # Run as non-root user.
    devices:
      - /dev/dri:/dev/dri:rw # Required for transcoding; renderD128 is usually GPU0.
    environment:
      JELLYFIN_PublishedServerUrl: "https://${JELLYFIN_URL}" # Configures the external URL.
    expose:
      - 8096/tcp # Web interface; reverse proxied at ${JELLYFIN_URL}.
    networks:
      - external
    tmpfs:
      - "/tmp:uid=${PUID},gid=${PGID}" # Required for read-only image.
    volumes:
      - /etc/localtime:/etc/localtime:ro # Sets the timezone.
      - jellyfin-cache:/cache:rw # Jellyfin cache storage.
      - jellyfin-config:/config:rw # Jellyfin configuration storage.
      - media-library:/library:ro # Media library mount. Read-only.
    cap_drop:
      - ALL # Drop all unnecessary privileges.
    deploy:
      resources:
        limits:
          cpus: 4 # Allow using up to 4 CPU cores.
          memory: 4G # Allow using up to 4GB of RAM.
    group_add:
      - "${RENDER_PGID}" # Required for transcoding.
    healthcheck:
      test: "curl --fail --retry 0 --silent http://127.0.0.1:8096/health || exit 1"
    security_opt:
      - no-new-privileges:true # Prevent privilege escalation.

networks:
  external:
    external: true
    name: external-network

volumes:
  jellyfin-cache:
    external: true
    name: jellyfin-cache-volume
  jellyfin-config:
    external: true
    name: jellyfin-config-volume
  media-library:
    name: media-library-bind
    driver_opts:
      device: "${MEDIA_LIBRARY_PATH}"
      o: bind
      type: none
