# Gatus: Status page and uptime monitoring.
# https://gatus.io

---
services:
  gatus:
    image: ghcr.io/twin/gatus:latest
    container_name: gatus
    env_file: ../../.env # Required for parsing environment variables in the config.
    hostname: gatus
    read_only: true
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    environment:
      DOCKER_HOST: "tcp://socket-proxy:2375"
      GATUS_DB_PASSWORD: "${GATUS_DB_PASSWORD}"
      GATUS_URL: "${GATUS_URL}"
      SOCKET_PROXY_URL: "http://socket-proxy:2375/v1.51/containers/"
      TZ: "${TZ}"
    expose:
      - 8080/tcp
    networks:
      - external
      - internal
    volumes:
      - ./config:/config:ro
    cap_drop:
      - ALL
    depends_on:
      gatus-db:
        condition: service_healthy
        restart: true
      socket-proxy:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 256M
    security_opt:
      - no-new-privileges:true # Prevent privilege escalation.

networks:
  external:
    external: true
    name: external-network
  internal:
    external: true
    name: internal-network
