---
services:
  ###########################################################################
  # Homepage: Dashboard - https://github.com/gethomepage/homepage           #
  ###########################################################################

  homepage:
    image: homepage
    container_name: homepage
    env_file: ../../.env
    hostname: homepage
    restart: unless-stopped
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "${HOMEPAGE_URL}" # Only allow HOMEPAGE_URL.
      PGID: "${PGID}" # Local group to run as.
      PUID: "${PUID}" # Local user to run as.
      TZ: "${TZ}" # Configures the timezone to use.
    expose:
      - 3000/tcp # Web interface.
    networks:
      - caddy
      - gluetun
      - socket-proxy
    cap_drop:
      - AUDIT_WRITE
      - MKNOD
      - SYS_CHROOT
    depends_on:
      socket-proxy:
        condition: service_healthy
        restart: true
    security_opt:
      - no-new-privileges:true

networks:
  caddy:
    external: true
    name: caddy-network # $ docker network create caddy-network
  socket-proxy:
    external: true # $ docker network create --internal=true socket-proxy-network
    internal: true # Isolates the network from the outside.
    name: socket-proxy-network # Internal-only network used only for Socket Proxy traffic.

  gluetun:
    driver: bridge
    external: true
    ipam:
      config:
        - subnet: 172.19.0.0/16 # Use 172.19.0.0/16 as a static subnet.
          gateway: 172.19.0.1 # Use 172.19.0.1 as the default gateway.
    name: gluetun-network # $ docker network create gluetun-network

volumes:
  socket-proxy:
    external: true
    name: socket-proxy-volume
