# Backrest: Web UI and orchestrator for Restic backups.
# https://garethgeorge.github.io/backrest/introduction/getting-started

---
services:
  backrest:
    image: ghcr.io/garethgeorge/backrest:v1.12
    container_name: backrest
    hostname: backrest
    read_only: true
    restart: unless-stopped
    environment:
      BACKREST_CONFIG: "/config/config.json"
      BACKREST_DATA: "/data"
      DOCKER_PATH: "${DOCKER_PATH}" # Path to Docker data.
      TMPDIR: "/tmp"
      TZ: "${TZ}"
      XDG_CACHE_HOME: "/cache"
    expose:
      - 9898/tcp # Web interface proxied internally at backrest.${INTERNAL_DOMAIN}.
    networks:
      - external
      - internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker socket mount.
      - backrest-cache:/cache:rw # Backrest cache.
      - backrest-config:/config:rw # Backrest configuration.
      - backrest-data:/data:rw # Backrest data.
      - backrest-tmp:/tmp:rw # Backrest tmp files.
      - backups:/mnt/backups:rw # Mounted local backups HDD.
      - docker:/mnt/docker:ro # Mounted local Docker data path.
      - storage:/mnt/storage:ro # Root storage directory.
    cap_drop:
      - AUDIT_WRITE
      - MKNOD
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    deploy:
      resources:
        limits:
          cpus: 4 # Allow using up to 4 CPU cores.
          memory: 8G # Allow using up to 8GB of RAM.
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://127.0.0.1:9898 || exit 1"
    security_opt:
      - no-new-privileges:true # Prevents privelege escalation.

networks:
  external:
    external: true
    name: external-network
  internal:
    external: true
    name: internal-network

volumes:
  backrest-data:
    name: backrest-data-volume
    external: true
  backrest-cache:
    name: backrest-cache-volume
    external: true
  backrest-config:
    name: backrest-config-volume
    external: true
  backrest-tmp:
    name: backrest-tmp-volume
    external: true
  backups:
    name: backups-hdd-bind
    driver_opts:
      device: "${BACKUPS_PATH}"
      o: bind
      type: none
  docker:
    name: docker-bind
    driver_opts:
      device: "${DOCKER_PATH}"
      o: bind
      type: none
  storage:
    name: storage-bind
    driver_opts:
      device: "${STORAGE_PATH}"
      o: bind
      type: none
