# Beszel: Server monitoring agent and hub.
# https://beszel.dev/guide/getting-started

---
# Default container options.
x-defaults: &defaults
  read_only: true
  restart: unless-stopped
  tmpfs:
    - "/tmp:uid=${PUID},gid=${PGID}" # Required for read-only image.
  cap_drop: # Drop as many privileges as possible.
    - AUDIT_WRITE
    - MKNOD
    - SETFCAP
    - SETPCAP
    - SYS_ADMIN
    - SYS_CHROOT
    - SYS_PTRACE
  deploy:
    resources:
      limits:
        cpus: 1 # Allow using up to 1 CPU core.
        memory: 128M # Allow using up to 128MB of RAM.
  security_opt:
    - no-new-privileges:true # Prevent privilege escalation.

services:
  # Beszel: Hub and interface for Beszel agents to connect to.
  beszel:
    <<: *defaults
    image: ghcr.io/henrygd/beszel/beszel:0.18
    container_name: beszel
    hostname: beszel
    user: "${PUID}:${PGID}" # Run as non-root user.
    ports:
      - 127.0.0.1:8090:8090/tcp # Expose the hub locally.
    networks:
      - external
      - internal
    volumes:
      - /etc/localtime:/etc/localtime:ro # Sets the timezone.
      - beszel-data:/beszel_data:rw # Beszel hub configuration and data.
      - beszel-socket:/beszel_socket:rw # Beszel socket mount.
    cap_drop:
      - ALL # Drop all unnecessary privileges.
    healthcheck:
      interval: 1m
      start_period: 5s
      test: ["CMD", "/beszel", "health --url http://127.0.0.1:8090"]

  # Beszel Agent: System monitoring agent.
  beszel-agent:
    <<: *defaults
    image: ghcr.io/henrygd/beszel/beszel-agent-intel:0.18 # Use -intel for Intel GPU support.
    container_name: beszel-agent
    hostname: beszel-agent
    network_mode: host # Required for accurate network statistics.
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128:rw # Required for GPU monitoring; renderD128 is usually GPU0.
    environment:
      HUB_URL: http://localhost:8090 # Connect to the local Beszel hub.
      LISTEN: /beszel_socket/beszel.sock # Listen on the mounted Beszel socket.
      KEY: "${BESZEL_KEY}" # Beszel hub key to register with.
      TOKEN: "${BESZEL_TOKEN}" # Beszel hub token to register with.
    volumes:
      - /etc/localtime:/etc/localtime:ro # Sets the timezone.
      - /var/run/docker.sock:/var/run/docker.sock:ro # Connects to the Docker socket.
      - beszel-agent:/var/lib/beszel-agent:rw # Beszel agent storage.
      - beszel-socket:/beszel_socket:rw # Beszel socket mount.
    cap_add:
      - CAP_PERFMON # Possibly required for GPU monitoring.
      - SYS_ADMIN # Possibly required for NVME SMART data.
      - SYS_RAWIO # Possibly required for SMART data.
    depends_on:
      beszel:
        condition: service_healthy # Require the beszel hub to be healthy before connecting.
        restart: true # Restart when the Beszel hub is restarted.
    healthcheck:
      interval: 1m
      test: ["CMD", "/agent", "health"]

networks:
  external:
    external: true
    name: external-network
  internal:
    external: true
    name: internal-network

volumes:
  beszel-agent:
    name: beszel-agent-volume
    external: true
  beszel-data:
    name: beszel-data-volume
    external: true
  beszel-socket:
    name: beszel-socket-volume
    external: true
