# Beszel: Server monitoring agent and hub.
# https://beszel.dev/guide/getting-started

---
# Default container options.
x-defaults: &defaults
  read_only: true
  restart: unless-stopped
  tmpfs:
    - "/tmp:uid=${PUID},gid=${PGID}" # Required for read-only image.
  deploy:
    resources:
      limits:
        cpus: 1
        memory: 128M
  security_opt:
    - no-new-privileges:true

services:
  beszel:
    <<: *defaults
    image: ghcr.io/henrygd/beszel/beszel:0.18
    container_name: beszel
    hostname: beszel
    user: "${PUID}:${PGID}"
    ports:
      - 127.0.0.1:8090:8090/tcp # Expose the hub locally so the agent can connect in network_mode: host.
    networks:
      - external
      - internal
    volumes:
      - /etc/localtime:/etc/localtime:ro # Sets the timezone.
      - beszel-data:/beszel_data:rw # Beszel hub configuration and data.
      - beszel-socket:/beszel_socket:rw # Beszel socket mount.
    cap_drop:
      - ALL
    healthcheck:
      interval: 1m
      test: ["CMD", "/beszel", "health --url http://127.0.0.1:8090"]

  beszel-agent:
    <<: *defaults
    image: ghcr.io/henrygd/beszel/beszel-agent:0.18
    container_name: beszel-agent
    hostname: beszel-agent
    network_mode: host # Required for accurate network statistics.
    environment:
      HUB_URL: "http://localhost:8090" # Connect to the local Beszel hub.
      LISTEN: "/beszel_socket/beszel.sock" # Listen on the mounted Beszel socket.
      KEY: "${BESZEL_KEY}" # Beszel hub key to register with.
      TOKEN: "${BESZEL_TOKEN}" # Beszel hub token to register with.
    volumes:
      - /etc/localtime:/etc/localtime:ro # Sets the timezone.
      - /var/run/docker.sock:/var/run/docker.sock:ro # Connects to the Docker socket.
      - beszel-agent:/var/lib/beszel-agent:rw # Beszel agent storage.
      - beszel-socket:/beszel_socket:rw # Beszel socket mount.
    cap_add:
      - SYS_ADMIN # Required for NVME SMART data.
      - SYS_RAWIO # Required for SMART data.
    cap_drop:
      - AUDIT_WRITE
      - MKNOD
      - SETFCAP
      - SETPCAP
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    depends_on:
      beszel:
        condition: service_healthy
        restart: true
    healthcheck:
      interval: 1m
      test: ["CMD", "/agent", "health"]

networks:
  external:
    external: true
    name: external-network
  internal:
    external: true
    name: internal-network

volumes:
  beszel-agent:
    name: beszel-agent-volume
    external: true
  beszel-data:
    name: beszel-data-volume
    external: true
  beszel-socket:
    name: beszel-socket-volume
    external: true
