# Radarr: Movie manager, organizer, and PVR.
# https://radarr.video/

---
services:
  radarr:
    image: ghcr.io/11notes/radarr:6
    container_name: radarr
    hostname: radarr
    read_only: true # Prevent writing directly to the image.
    restart: unless-stopped
    environment:
      TZ: "${TZ}" # Sets the timezone.
    expose:
      - 7878/tcp # Web interface; reverse proxied at radarr.${INTERNAL_DOMAIN}.
    networks:
      - external
      - gluetun
      - internal
    tmpfs:
      - "/tmp:uid=1000,gid=1000" # Required for read-only image.
    volumes:
      - downloads:/downloads:rw # Completed downloads mount.
      - media-library:/library:rw # Media library mount.
      - radarr:/radarr/etc:rw # Radarr configuration storage.
    cap_drop:
      - ALL # Drop all unnecessary privileges.
    depends_on:
      arr-db:
        condition: service_healthy # Require arr-db to be healthy before starting.
        restart: true # Restart when arr-db restarts.
    deploy:
      resources:
        limits:
          cpus: 2 # Allow using up to 2 CPU cores.
          memory: 4G # Allow using up to 4GB of RAM.
    security_opt:
      - no-new-privileges:true # Prevent privilege escalation.

networks:
  external:
    external: true
    name: external-network
  gluetun:
    external: true
    name: gluetun-network
  internal:
    external: true
    name: internal-network

volumes:
  radarr:
    name: radarr-volume
    external: true
  downloads:
    name: downloads-bind
    driver_opts:
      device: "${DOWNLOADS_PATH}"
      o: bind
      type: none
  media-library:
    name: media-library-bind
    driver_opts:
      device: "${MEDIA_LIBRARY_PATH}"
      o: bind
      type: none
