# arr-db: PostgreSQL container used for 'ARR apps.
# Each 'ARR app will have to be configured to use this, see docs.

---
services:
  arr-db:
    image: ghcr.io/11notes/postgres:18
    container_name: arr-db
    hostname: arr-db
    read_only: true
    shm_size: 512M
    environment:
      POSTGRES_BACKUP_RETENTION: "7" # Retain backups for 7 days.
      POSTGRES_BACKUP_SCHEDULE: "0 6 * * *" # Backup daily at 6:00 AM.
      POSTGRES_PASSWORD: "${ARR_DB_PASSWORD}" # Sets the PostgreSQL password.
      TZ: "${TZ}"
    networks:
      - internal
      - gluetun
    tmpfs:
      - "/postgres/log:uid=1000,gid=1000" # Required for read-only image.
      - "/postgres/run:uid=1000,gid=1000" # Required for read-only image.
    volumes:
      - arr-db-backups:/postgres/backup:rw # PostgreSQL backup storage.
      - arr-db-config:/postgres/etc:rw # PostgreSQL configuration storage.
      - arr-db-data:/postgres/var:rw # PostgreSQL database storage.
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
    security_opt:
      - no-new-privileges:true # Prevent privilege escalation.

networks:
  gluetun:
    external: true
    name: gluetun-network
  internal:
    external: true
    name: internal-network

volumes:
  arr-db-backups:
    name: arr-db-backups-volume
    external: true
  arr-db-config:
    name: arr-db-config-volume
    external: true
  arr-db-data:
    name: arr-db-data-volume
    external: true
