# Sonarr: Anime/TV series manager, organizer, and PVR.
# https://sonarr.tv

---
services:
  sonarr:
    image: ghcr.io/11notes/sonarr:4
    container_name: sonarr
    hostname: sonarr
    read_only: true
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
    expose:
      - 8989/tcp # Web interface; reverse proxied at sonarr.${INTERNAL_DOMAIN}.
    networks:
      - external
      - gluetun
      - internal
    tmpfs:
      - "/tmp:uid=1000,gid=1000" # Required for read-only image.
    volumes:
      - downloads:/downloads:rw # Completed downloads mount.
      - media-library:/library:rw # Media library mount.
      - sonarr:/sonarr/etc:rw # Sonarr configuration storage.
    cap_drop:
      - ALL
    depends_on:
      arr-db:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2G
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://127.0.0.1:8989/api/v3/system/status?apikey=${SONARR_API_KEY} || exit 1"
    security_opt:
      - no-new-privileges:true

networks:
  external:
    external: true
    name: external-network
  gluetun:
    external: true
    name: gluetun-network
  internal:
    external: true
    name: internal-network

volumes:
  sonarr:
    name: sonarr-volume
    external: true
  downloads:
    name: downloads-bind
    driver_opts:
      device: "${DOWNLOADS_PATH}"
      o: bind
      type: none
  media-library:
    name: media-library-bind
    driver_opts:
      device: "${MEDIA_LIBRARY_PATH}"
      o: bind
      type: none
