# Gluetun: VPN client. I'm currently using AirVPN.
# Many of these options are redundant to explicitly set, but I do so anyways
# as Gluetun has a habit of randomly changing defaults from time-to-time.
# https://github.com/qdm12/gluetun-wiki/tree/main/setup/options

---
services:
  gluetun:
    image: ghcr.io/qdm12/gluetun:latest
    container_name: gluetun
    hostname: gluetun
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun:rw # Wireguard TUN/TAP device.
    environment:
      BLOCK_MALICIOUS: "off" # Disable unbound; lowers resource usage heavily.
      DNS_UPDATE_PERIOD: "24h" # Update DNS every 24 hours.
      DNS_UPSTREAM_RESOLVER_TYPE: "doh" # Use DNS over HTTPS until DOT is more stable.
      DNS_UPSTREAM_RESOLVERS: "libredns,quad9" # Use LibreDNS and Quad9 as DNS resolvers.
      FIREWALL_OUTBOUND_SUBNETS: "${FIREWALL_OUTBOUND_SUBNETS}" # Subnets to allow into the internal firewall.
      FIREWALL_VPN_INPUT_PORTS: "${FIREWALL_VPN_INPUT_PORTS}" # VPN-designated ports to forward (i.e AirVPN port for qBittorrent/Soulseek).
      GLUETUN_HTTP_CONTROL_SERVER_ENABLE: "on" # Enables the control server.
      HEALTH_ICMP_TARGET_IPS: "116.202.176.26,9.9.9.9" # Target LibreDNS and Quad9 for healthchecks.
      HEALTH_TARGET_ADDRESSES: "libredns.gr:443,quad9.net:443" # Target LibreDNS and Quad9 for healthchecks.
      HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE: '{"auth":"apikey","apikey":"${GLUETUN_API_KEY}"}' # Configures auth for the control server.
      PGID: "${PGID}" # Group ID to run as.
      PORT_FORWARD_ONLY: "${PROTONVPN_PORT_FORWARDING:-false}" # Only enable if using ProtonVPN. Enables port forwarding.
      PUID: "${PUID}" # User ID to run as.
      SERVER_CITIES: "${SERVER_CITIES}" # List of server cities to connect to.
      SERVER_COUNTRIES: "${SERVER_COUNTRIES}" # List of server countries to connect to.
      SERVER_REGIONS: "${SERVER_REGIONS}" # List of server regions to connect to.
      TZ: "${TZ}" # Timezone to use.
      UPDATER_PERIOD: "24h" # Update server data every 24 hours.
      UPDATER_PROTONVPN_EMAIL: "${UPDATER_PROTONVPN_EMAIL}" # If using ProtonVPN, email to authenticate with.
      UPDATER_PROTONVPN_PASSWORD: "${UPDATER_PROTONVPN_PASSWORD}" # If using ProtonVPN, password to authenticate with.
      VPN_PORT_FORWARDING: "${PROTONVPN_PORT_FORWARDING:-false}" # Only enable if using ProtonVPN.
      VPN_SERVICE_PROVIDER: "${VPN_SERVICE_PROVIDER}" # https://github.com/qdm12/gluetun-wiki/blob/main/setup/providers
      VPN_TYPE: "wireguard" # Use Wireguard instead of OpenVPN.
      WIREGUARD_ADDRESSES: "${WIREGUARD_ADDRESSES}" # List of Wireguard addresses to connect to.
      WIREGUARD_ENDPOINT_PORT: "${WIREGUARD_ENDPOINT_PORT}" # Wireguard port to connect to.
      WIREGUARD_MTU: "${WIREGUARD_MTU}" # If set, overrides auto-MTU detection.
      WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL: "${WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL}" # Custom keepalive interval.
      WIREGUARD_PRESHARED_KEY: "${WIREGUARD_PRESHARED_KEY}" # PresharedKey from Wireguard config file.
      WIREGUARD_PRIVATE_KEY: "${WIREGUARD_PRIVATE_KEY}" # PrivateKey from Wireguard config file.
      WIREGUARD_PUBLIC_KEY: "${WIREGUARD_PUBLIC_KEY}" # PublicKey from Wireguard config file.
    expose:
      - 8080/tcp # qBittorrent.
    networks:
      - gluetun
    volumes:
      - gluetun:/gluetun:rw
    cap_add:
      - NET_ADMIN # Required for configuring Wireguard.
      - NET_RAW # Required for raw ICMP healthchecks.
    cap_drop:
      - AUDIT_WRITE
      - MKNOD
      - SETFCAP
      - SETPCAP
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
    security_opt:
      - no-new-privileges:true

networks:
  external:
    external: true
    name: external-network
  gluetun:
    external: true
    name: gluetun-network
  internal:
    external: true
    name: internal-network

volumes:
  gluetun:
    name: gluetun-volume
    external: true
