# Gluetun: VPN client. I'm currently using AirVPN.
# https://github.com/qdm12/gluetun-wiki/tree/main/setup/options

---
services:
  gluetun:
    image: ghcr.io/qdm12/gluetun:latest
    container_name: gluetun
    hostname: gluetun
    restart: unless-stopped
    devices:
      - /dev/net/tun:/dev/net/tun:rw
    environment:
      BLOCK_MALICIOUS: "off" # Disables unbound; saves a lot of memory.
      DNS_UPDATE_PERIOD: "24h"
      DNS_UPSTREAM_RESOLVER_TYPE: "doh" # Currently using DOH due to DOT issues.
      DNS_UPSTREAM_RESOLVERS: "libredns,quad9" # Use LibreDNS and Quad9.
      FIREWALL_OUTBOUND_SUBNETS: "${FIREWALL_OUTBOUND_SUBNETS}"
      FIREWALL_VPN_INPUT_PORTS: "${FIREWALL_VPN_INPUT_PORTS}"
      GLUETUN_HTTP_CONTROL_SERVER_ENABLE: "on" # Enables the control server.
      HEALTH_ICMP_TARGET_IPS: "116.202.176.26,9.9.9.9" # LibreDNS and Quad9.
      HEALTH_TARGET_ADDRESSES: "libredns.gr:443,quad9.net:443" # Test against LibreDNS and Quad9.
      HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE: '{"auth":"apikey","apikey":"${GLUETUN_API_KEY}"}' # Enables the control server. https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/control-server.md
      PGID: "${PGID}"
      PUID: "${PUID}"
      SERVER_CITIES: "${SERVER_CITIES}"
      SERVER_COUNTRIES: "${SERVER_COUNTRIES}"
      TZ: "${TZ}"
      UPDATER_PERIOD: "24h"
      VPN_SERVICE_PROVIDER: "${VPN_SERVICE_PROVIDER}"
      VPN_TYPE: "wireguard"
      WIREGUARD_ADDRESSES: "${WIREGUARD_ADDRESSES}"
      WIREGUARD_ENDPOINT_PORT: "${WIREGUARD_ENDPOINT_PORT}"
      WIREGUARD_MTU: "${WIREGUARD_MTU}" # Overrides automatic MTU discovery in v3.41.
      WIREGUARD_PERSISTENT_KEEPALIVE_INTERVAL: "25s" # Keep connections alive a little longer.
      WIREGUARD_PRESHARED_KEY: "${WIREGUARD_PRESHARED_KEY}"
      WIREGUARD_PRIVATE_KEY: "${WIREGUARD_PRIVATE_KEY}"
      WIREGUARD_PUBLIC_KEY: "${WIREGUARD_PUBLIC_KEY}"
    expose:
      - 5030/tcp # slskd web interface.
      - 7476/tcp # qui web interface.
      - 8080/tcp # qBittorrent web interface.
      - 8191/tcp # Byparr server.
      - 9696/tcp # Prowlarr web interface.
    networks:
      - gluetun
    volumes:
      - gluetun:/gluetun:rw
    cap_add:
      - NET_ADMIN
      - NET_RAW
    cap_drop:
      - AUDIT_WRITE
      - MKNOD
      - SETFCAP
      - SETPCAP
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
    security_opt:
      - no-new-privileges:true

networks:
  external:
    external: true
    name: external-network
  gluetun:
    external: true
    name: gluetun-network
  internal:
    external: true
    name: internal-network

volumes:
  gluetun:
    name: gluetun-volume
    external: true
