# Prowlarr: Indexer manager for 'ARR apps.
# https://prowlarr.com

---
services:
  prowlarr:
    image: ghcr.io/11notes/prowlarr:2.3
    container_name: prowlarr
    network_mode: service:gluetun
    read_only: true
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
    tmpfs:
      - "/tmp:uid=1000,gid=1000"
    volumes:
      - prowlarr:/prowlarr/etc:rw
    depends_on:
      media-db:
        condition: service_healthy
        restart: true
      gluetun:
        condition: service_healthy
        restart: true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
    security_opt:
      - no-new-privileges:true

volumes:
  prowlarr:
    name: prowlarr-volume
    external: true
