# Prowlarr: Indexer manager and synchronization for 'ARR apps.
# https://prowlarr.com/

---
services:
  prowlarr:
    image: ghcr.io/11notes/prowlarr:2
    container_name: prowlarr
    network_mode: service:gluetun # Route all traffic through gluetun.
    read_only: true # Prevent writing directly to the image.
    restart: unless-stopped
    environment:
      TZ: "${TZ}" # Sets the timezone.
    tmpfs:
      - "/tmp:uid=1000,gid=1000" # Required for read-only image.
    volumes:
      - prowlarr:/prowlarr/etc:rw # Prowlarr configuration storage.
    depends_on:
      arr-db:
        condition: service_healthy # Require arr-db to be healthy before starting.
        restart: true # Restart when arr-db restarts.
      gluetun:
        condition: service_healthy # Require Gluetun to be healthy before starting.
        restart: true # Restart when Gluetun restarts.
    cap_drop:
      - ALL # Drop all unnecessary privileges.
    deploy:
      resources:
        limits:
          cpus: 1 # Allow using up to 1 CPU core.
          memory: 1G # Allow using up to 1GB of RAM.
    security_opt:
      - no-new-privileges:true # Prevent privilege escalation.

networks:
  gluetun:
    external: true
    name: gluetun-network

volumes:
  prowlarr:
    name: prowlarr-volume
    external: true
