# Chhoto URL: URL forwarder and shortener.
# https://github.com/sintan1729/chhoto-url

---
services:
  chhoto:
    image: ghcr.io/sintan1729/chhoto-url:6.5-alpine
    container_name: chhoto
    hostname: chhoto
    read_only: true # Prevent writing directly to the image.
    restart: unless-stopped
    user: "${PUID}:${PGID}" # Run as non-root user.
    environment:
      api_key: "${CHHOTO_API_KEY}" # Sets the API key. $ openssl rand -hex 32
      db_url: "/db/urls.sqlite" # SQLite database file to use.
      ensure_acid: "True" # Ensures ACID compliance.
      password: "${CHHOTO_PASSWORD}" # Sets the password.
      site_url: "https://${CHHOTO_URL}" # Sets the URL to use for forwarding.
      slug_style: "Pair" # Use paired slug styling.
      TZ: "${TZ}" # Sets the timezone.
      use_wal_mode: "True" # Use WAL mode for SQLite.
    expose:
      - 4567/tcp # Web interface; reverse proxied at ${CHHOTO_URL}.
    networks:
      - external
    volumes:
      - chhoto:/db:rw # Chhoto database storage.
    cap_drop:
      - ALL # Drop all unnecessary privileges.
    deploy:
      resources:
        limits:
          cpus: 0.5 # Allow using up to 0.5 CPU cores.
          memory: 128M # Allow using up to 128MB of RAM.
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://127.0.0.1:4567/api/whoami || exit 1"
    security_opt:
      - no-new-privileges:true # Prevent privilege escalation.

networks:
  external:
    external: true
    name: external-network

volumes:
  chhoto:
    external: true
    name: chhoto-volume
