# Bazarr: Subtitle manager for media.
# https://www.bazarr.media

---
services:
  bazarr:
    image: ghcr.io/hotio/bazarr:release
    container_name: bazarr
    hostname: bazarr
    restart: unless-stopped
    environment:
      PGID: "${PGID}"
      POSTGRES_DATABASE: "postgres"
      POSTGRES_ENABLED: "true"
      POSTGRES_HOST: "arr-db"
      POSTGRES_PASSWORD: "${ARR_DB_PASSWORD}"
      POSTGRES_PORT: "5432"
      POSTGRES_USERNAME: "postgres"
      PUID: "${PUID}"
      TZ: "${TZ}"
      UMASK: "${UMASK}"
    expose:
      - 6767/tcp # Web interface reverse proxied internally at bazarr.${INTERNAL_DOMAIN}.
    networks:
      - external
      - internal
    volumes:
      - media-library:/library:rw # Root media library directory.
      - bazarr:/config:rw # Bazarr configuration and data.
    cap_drop:
      - AUDIT_WRITE
      - MKNOD
      - SETFCAP
      - SETPCAP
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    depends_on:
      arr-db:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
    healthcheck:
      test: "curl --fail --retry 0 --silent http://127.0.0.1:6767/ || exit 1"
    security_opt:
      - no-new-privileges:true

networks:
  external:
    external: true
    name: external-network
  internal:
    external: true
    name: internal-network

volumes:
  bazarr:
    name: bazarr-volume
    external: true
  media-library:
    name: media-library-bind
    driver_opts:
      device: "${MEDIA_LIBRARY_PATH}"
      o: bind
      type: none
