# Bazarr: Subtitle manager and synchronization for 'ARR apps.
# https://www.bazarr.media

---
services:
  bazarr:
    image: ghcr.io/hotio/bazarr:release
    container_name: bazarr
    hostname: bazarr
    restart: unless-stopped
    environment:
      PGID: "${PGID}" # Group ID to run as.
      POSTGRES_DATABASE: "postgres" # PostgreSQL database.
      POSTGRES_ENABLED: "true" # Enable PostgreSQL.
      POSTGRES_HOST: "arr-db" # PostgreSQL hostname.
      POSTGRES_PASSWORD: "${ARR_DB_PASSWORD}" # PostgreSQL password.
      POSTGRES_PORT: "5432" # PostgreSQL port.
      POSTGRES_USERNAME: "postgres" # PostgreSQL username.
      PUID: "${PUID}" # User ID to run as.
      TZ: "${TZ}" # Sets the timezone.
      UMASK: "${UMASK}" # Default umask to apply.
    expose:
      - 6767/tcp # Web interface reverse proxied internally at bazarr.${INTERNAL_DOMAIN}.
    networks:
      - external
      - internal
    volumes:
      - media-library:/library:rw # Root media library directory.
      - bazarr:/config:rw # Configuration and data.
    depends_on:
      arr-db:
        condition: service_healthy # Require arr-db to be healthy before starting.
        restart: true # Restart when arr-db restarts.
    cap_drop: # Drop all unnecessary privileges.
      - AUDIT_WRITE
      - MKNOD
      - SETFCAP
      - SETPCAP
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    deploy:
      resources:
        limits:
          cpus: 1 # Allow using up to 1 CPU core.
          memory: 1G # Allow using up to 1GB of RAM.
    security_opt:
      - no-new-privileges:true # Prevent privilege escalation.
    healthcheck:
      test: "curl --fail --retry 0 --silent http://127.0.0.1:6767/ || exit 1"

networks:
  external:
    external: true
    name: external-network
  internal:
    external: true
    name: internal-network

volumes:
  bazarr:
    name: bazarr-volume
    external: true
  media-library:
    name: media-library-bind
    driver_opts:
      device: "${MEDIA_LIBRARY_PATH}"
      o: bind
      type: none
