services:
  ###########################################################################
  # Bazarr: Subtitle manager - https://wiki.bazarr.media                    #
  ###########################################################################

  bazarr:
    image: ghcr.io/hotio/bazarr:release-1.5.3
    container_name: bazarr
    restart: unless-stopped
    environment:
      PGID: "${PGID}"
      POSTGRES_DATABASE: "postgres"
      POSTGRES_ENABLED: "true"
      POSTGRES_HOST: "bazarr-db"
      POSTGRES_PASSWORD: "${BAZARR_DB_PASSWORD}"
      POSTGRES_PORT: "5432"
      POSTGRES_USERNAME: "postgres"
      PUID: "${PUID}"
      TZ: "${TZ}"
      UMASK: "${UMASK}"
    expose:
      - 6767/tcp
    networks:
      caddy:
      gluetun:
        ipv4_address: 172.19.0.23
      internal-only:
    volumes:
      - bazarr:/config
      - media-library:/library
    cap_add:
      - CHOWN
      - FOWNER
      - FSETID
      - SETGID
      - SETUID
    cap_drop:
      - ALL
    depends_on:
      bazarr-db:
        condition: service_healthy
        restart: true
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 2048M
    security_opt:
      - no-new-privileges:true

  bazarr-db:
    image: ghcr.io/11notes/postgres:17
    container_name: bazarr-db
    hostname: bazarr-db
    read_only: true
    restart: unless-stopped
    environment:
      POSTGRES_BACKUP_SCHEDULE: "0 6 * * *"
      POSTGRES_PASSWORD: "${BAZARR_DB_PASSWORD}"
      TZ: "${TZ}"
    networks:
      - internal-only
    tmpfs:
      - "/postgres/log:uid=${PUID},gid=${PGID}"
      - "/postgres/run:uid=${PUID},gid=${PGID}"
    volumes:
      - bazarr-db-backups:/postgres/backup
      - bazarr-db-config:/postgres/etc
      - bazarr-db-data:/postgres/var
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1024M
    security_opt:
      - no-new-privileges:true

networks:
  caddy:
    external: true
    name: caddy-network
  gluetun:
    driver: bridge
    external: true
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
    name: gluetun-network
  internal-only:
    driver: bridge
    external: true
    internal: true
    name: internal-only-network

volumes:
  bazarr:
    name: bazarr-volume
    external: true
  bazarr-db-data:
    name: bazarr-db-data-volume
    external: true
  bazarr-db-config:
    name: bazarr-db-config-volume
    external: true
  bazarr-db-backups:
    name: bazarr-db-backups-volume
    external: true
