---
services:
  ###########################################################################
  # Bazarr: Subtitle manager - https://wiki.bazarr.media                    #
  ###########################################################################

  bazarr:
    image: ghcr.io/hotio/bazarr:release
    container_name: bazarr
    hostname: bazarr
    restart: unless-stopped
    environment:
      PGID: "${PGID}" # Group ID to run as.
      POSTGRES_URL: "postgres://postgres:${BAZARR_DB_PASSWORD}@bazarr-db:5432/postgres" # PostgreSQL connection URL.
      PUID: "${PUID}" # User ID to run as.
      TZ: "${TZ}" # Sets the timezone.
      UMASK: "${UMASK}" # Umask to apply to newly created files.
    expose:
      - 6767/tcp # Web interface reverse proxied internally at bazarr.${INTERNAL_DOMAIN}.
    networks:
      - caddy
      - internal-only
    volumes:
      - media-library:/library:rw # Root media library directory.
      - bazarr:/config:rw # Configuration and data.
    cap_drop:
      - AUDIT_WRITE
      - MKNOD
      - SETFCAP
      - SETPCAP
      - SYS_ADMIN
      - SYS_CHROOT
      - SYS_PTRACE
    depends_on:
      bazarr-db:
        condition: service_healthy # Wait for bazarr-db to be healthy before starting.
        restart: true # Restart when bazarr-db restarts.
    deploy:
      resources:
        limits:
          cpus: 1 # Allow using 2 vCPUs.
          memory: 1G # Allow using 2GB.
    healthcheck:
      test: "curl -f http://127.0.0.1:6767/api/system/health?apikey=${BAZARR_API_KEY} || exit 1"
    security_opt:
      - no-new-privileges:true # Do not allow privilege escalation.

  bazarr-db:
    image: ghcr.io/11notes/postgres:17
    container_name: bazarr-db
    hostname: bazarr-db
    read_only: true
    restart: unless-stopped
    environment:
      POSTGRES_BACKUP_SCHEDULE: "0 6 * * *" # Run every night at 6AM.
      POSTGRES_PASSWORD: "${BAZARR_DB_PASSWORD}" # Configures the default PostgreSQL password.
      TZ: "${TZ}" # Sets the timezone.
    networks:
      - internal-only
    tmpfs:
      - "/postgres/log:uid=${PUID},gid=${PGID}" # Required for read_only image.
      - "/postgres/run:uid=${PUID},gid=${PGID}" # Required for read_only image.
    volumes:
      - bazarr-db-backups:/postgres/backup:rw # PostgreSQL backups.
      - bazarr-db-config:/postgres/etc:rw # PostgreSQL configuration.
      - bazarr-db-data:/postgres/var:rw # PostgreSQL data.
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: 0.5 # Allow using 0.5 vCPUs.
          memory: 512M # Allow using 512MB.
    security_opt:
      - no-new-privileges:true # Do not allow privilege escalation.

networks:
  caddy:
    external: true
    name: caddy-network
  internal-only:
    external: true
    name: internal-only-network

volumes:
  bazarr-db-backups:
    name: bazarr-db-backups-volume
    external: true
  bazarr-db-config:
    name: bazarr-db-config-volume
    external: true
  bazarr-db-data:
    name: bazarr-db-data-volume
    external: true
  bazarr:
    name: bazarr-volume
    external: true
  media-library:
    name: media-library-bind
    driver_opts:
      device: "${MEDIA_LIBRARY_PATH}"
      o: bind
      type: none
