# Syncplay: Media playback synchronization tool for watch parties.
# https://syncplay.pl

---
services:
  syncplay:
    image: ghcr.io/dnomd343/syncplay:v1.7.5
    container_name: syncplay
    hostname: syncplay
    read_only: true # Prevent writing directly to the image.
    restart: unless-stopped
    user: "${PUID}:${PGID}" # Run as non-root user.
    environment:
      ENABLE_TLS: "true" # Enable TLS?
      MOTD: "${SYNCPLAY_MOTD}" # Sets the MOTD.
      PASSWORD: "${SYNCPLAY_PASSWORD}" # Sets the password.
    networks:
      - external
    expose:
      - 8999/tcp # Syncplay server; reverse proxied at ${SYNCPLAY_URL}.
    tmpfs:
      - "/tmp:uid=${PUID},gid=${PGID},exec" # Required for read-only image.
    volumes:
      - /etc/localtime:/etc/localtime:ro # Local timezone mount.
      - syncplay-certs:/certs:rw # Syncplay certificate storage volume.
      - syncplay-data:/data:rw # Syncplay data volume.
    cap_drop:
      - ALL # Drop all unnecessary privileges.
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 256M
    security_opt:
      - no-new-privileges:true # Prevent privilege escalation.

networks:
  external:
    external: true
    name: external-network

volumes:
  syncplay-certs:
    name: syncplay-certs-volume
    external: true
  syncplay-data:
    name: syncplay-data-volume
    external: true
