directory: /library/music # Path to the music library.
library: /config/musiclibrary.blb # Save the beets library to the volume.
plugins: fetchart ftintitle lastgenre lyrics musicbrainz replaygain scrub zero # Plugins to enable.
threaded: yes # Enable multithreading.
languages: "en" # Use English names preferred.

# Matching/metadata options.
match:
  preferred:
    original_year: yes # Prefer the original year instead of the reissue year.
    countries: ["US", "GB", "XW"] # Heavily prioritize US, UK, and Worldwide releases.
    media: ["CD", "Digital Media|File"] # Target standard CD and high-quality digital files first.
original_date: yes # In Utero (1993) instead of In Utero (30th Anniversary) (2023).
per_disc_numbering: yes # Enable per-disk numbering.

# MusicBrainz configuration.
# Remove if you do not self-host a MusicBrainz server!
musicbrainz:
  host: host.docker.internal:5000
  https: no
  ratelimit: 1
  search_limit: 20
  extra_tags: [alias, barcode, catalognum, country, label, media, tracks, year]

# Import configuration.
import:
  copy: no # Do not copy files.
  hardlink: no # Do not hardlink files.
  incremental: yes # Skip processed items. Set this to false if you wanna run things again.
  move: no # Do not move files.
  quiet_fallback: skip # Skip files that cannot automatically be matched.
  resume: no # Do not resume if exited.
  timid: no # Do not run timidly; automatically tag matching releases.
  write: yes # Write changes to the files.

# Album art configuration.
art_filename: cover
fetchart:
  store_source: yes # Store the album art source. Helpful for debugging.
  auto: yes # Automatically fetch album art.
  enforce_ratio: yes # Require 1:1 images.
  fanarttv_key: "${FANARTTV_API_KEY}" # Automatically replaced by envsubstr since Beets doesn't support this.
  lastfm_key: "${LASTFM_API_KEY}" # Automatically replaced by envsubstr since Beets doesn't support this.
  maxwidth: 1200 # Max width of 1200x1200.
  quality: 100 # Use 100% quality for downscaled images.
  minwidth: 500 # Require album art to be 500x500 or larger.
  sources: [coverart, itunes, fanarttv, lastfm, filesystem] # Sources to enable.

# Acoustic fingerprinting configuration.
chroma:
  auto: yes # Automatically fingerprint and match unrecognized files.

# Feature in Title configuration.
ftintitle:
  auto: yes # Automatically move featured artists to the title.
  drop: no # Do not drop them entirely.
  format: (feat. {0}) # The format appended to the track title.

# Last.fm genre configuration.
lastgenre:
  auto: yes # Automatically fetch genre data from Last.fm.
  canonical: yes # Use canonical mapping black magic.
  count: 3 # Fetch the 3 most popular genres.
  force: yes # Force setting the genre tags.
  prefer_specific: true # Prefer setting specific tags (i.e Grunge instead of Rock) as the primary tag.

# Lyrics configuration.
lyrics:
  auto: yes # Automatically fetch lyrics.
  fallback: "" # Wipe existing lyrics if none are found.
  genius_api_key: "${GENIUS_API_KEY}" # Automatically replaced by envsubstr since Beets doesn't support this.
  sources: [lrclib, genius] # Sources to enable.
  synced: yes # Prefer synced lyrics.

# ReplayGain configuration.
replaygain:
  auto: yes # Automatically analyze and write tags during import.
  backend: ffmpeg # Use ffmpeg.
  overwrite: yes # Overwrite existing replaygain data.

# Tag scrubbing configuration.
scrub:
  auto: yes # Automatically scrub existing tags.
zero:
  fields: images comments encoder # Scrub useless stuff.
  update_database: true # Update the database when finished.
