directory: /library/music # Path to the music library.
library: /config/beets/library.db # Save the database inside of the container.
plugins: musicbrainz chroma lastgenre lyrics replaygain fetchart embedart scrub zero
threaded: yes # Enable multithreading.
original_date: yes # Prefer the original date over the issue date.
per_disc_numbering: yes # Enable per-disk numbering.

# Import configuration.
import:
  copy: no # Do not copy; let Lidarr handle moving.
  incremental: yes # Run incrementally.
  languages: en # Use transliterated artist names.
  link: no # Do not use hardlinks; let Lidarr handle moving.
  move: no # Do not move; let Lidarr handle moving.
  quiet_fallback: skip # Do not import failed items in quiet mode.
  resume: no # Do not auto resume interrupted imports.
  timid: no # Do not run in timid mode; enables the autotagger.
  write: yes # Write changes in-place.

# Matching configuration.
match:
  distance_weights:
    country: 0.2 # Lower country mismatch penalty.
    data_source: 0.0 # Disable data source penalty. Fixes self-hosted shit.
  max_rec:
    missing_tracks: medium # Require interaction for missing tracks.
    unmatched_tracks: medium # Require interaction for unmatched tracks.
  preferred:
    countries: ["US", "GB|UK", "CA", "AU", "XW"] # Prefer US, GB, CA, AU, and Worldwide releases.
    media: ["CD", "Digital Media|File"] # Prefer CDs and Digital Media.
    original_year: yes # Prefer the original year.
  rec_gap_thresh: 0.25 # Default medium match of 85%.
  strong_rec_thresh: 0.10 # Match items with a 90% match or above.

# Chromaprint configuration.
chroma:
  auto: yes # Enable fingerprint-based tagging.

# Fetched album artwork configuration.
fetchart:
  auto: yes # Automatically fetch album art.
  enforce_ratio: yes # Require album art to be 1:1.
  fanarttv_key: "${FANARTTV_API_KEY}"
  high_resolution: yes # Retrieve artwork at the highest resolution.
  lastfm_key: "${LASTFM_API_KEY}"
  maxwidth: 1200 # Downscale album art to 1200x1200.
  minwidth: 250 # Require album art to be 250x250 or larger.
  quality: 100 # Fetch maximum quality album art.
  store_source: yes # Store the Album Art source in the database.
  sources: [coverart, itunes, fanarttv, lastfm, filesystem] # Sources to enable.

# Embedded album artwork configuration.
embedart:
  auto: yes # Automatically embed album art.
  maxwidth: 1200 # Embed art up to 1200x1200.
  quality: 100 # Embed maximum-quality artwork.
  remove_art_file: no # Do not remove the album art file.

# Last.fm genre fetching configuration.
lastgenre:
  auto: yes # Automatically fetch genre data.
  canonical: yes # Use a canonicalization tree.
  count: 3 # Fetch the 3 most popular genres.
  fallback: "" # Reset genres if no data is found.
  force: yes # Always rewrite genre data.
  keep_existing: no # Do not keep existing genre data.
  prefer_specific: no # Use the most popular genre as the primary one.
  source: album # Use album genre data.
  title_case: yes # Convert genre tags to TitleCase.

# Lyric fetching configuration.
lyrics:
  auto: yes # Automatically fetch lyrics.
  fallback: "" # Reset lyrics if no match is found.
  force: yes # Always fetch lyrics.
  genius_api_key: "${GENIUS_API_KEY}"
  keep_synced: yes # Do not re-write synced lyrics if they already exist.
  sources: [lrclib, genius]
  synced: yes # Prefer synced lyrics.

# MusicBrainz configuration. Remove host and https if not self-hosting.
musicbrainz:
  extra_tags: [alias, barcode, catalognum, country, label, media, tracks, year] # Extra tags to return.
  host: host.docker.internal:5000 # Connect to internal self-hosted MusicBrainz server.
  https: no # Change this if reverse proxying MusicBrainz.

# ReplayGain configuration.
replaygain:
  auto: yes # Enable replaygain tagging.
  backend: ffmpeg # Use ffmpeg as the backend.
  overwrite: yes # Replace existing ReplayGain data.

# Scrubbing configuration.
scrub:
  auto: yes # Automatically scrub non-beets provided tags.
zero:
  auto: yes # Automatically zero fields on import.
  fields: comments # Remove comments.
  update_database: true # Update the database when finished.
