directory: /library/music # Path to the music library.
library: /config/musiclibrary.blb # Save the beets library to the volume.
plugins: chroma embedart fetchart ftintitle lastgenre lyrics replaygain scrub zero # Plugins to enable.
threaded: yes # Enable multithreading.

# Matching/metadata options.
match:
  preferred:
    original_year: yes # Prefer the original year instead of the reissue year.
original_date: yes # In Utero (1993) instead of In Utero (30th Anniversary) (2023).
per_disc_numbering: yes # Enable per-disk numbering.

# MusicBrainz configuration.
# Remove if you do not self-host a MusicBrainz server!
musicbrainz:
  host: host.docker.internal:5000
  https: no
  ratelimit: 100
  searchlimit: 20

# Import configuration.
import:
  copy: no # Do not copy files.
  hardlink: no # Do not hardlink files.
  incremental: yes # Skip processed items. Set this to false if you wanna run things again.
  log: /config/beets-logs/beet.log # Save log files.
  move: no # Do not move files.
  quiet_fallback: skip # Skip files that cannot automatically be matched.
  resume: no # Do not resume if exited.
  timid: no # Do not run timidly; automatically tag matching releases.
  write: yes # Write changes to the files.

# Album art configuration.
art_filename: cover
embedart:
  auto: yes # Automatically embed album art.
  maxwidth: 1500 # Save album art up to 1500x1500.
  remove_art_file: no # Do not remove the album art file.
  compare_threshold: 0 # Force Beets to always use the newly fetched art instead of getting stuck on old embedded garbage.
fetchart:
  auto: yes # Automatically fetch album art.
  cover_names: cover front back art folder album # Names to store files as.
  enforce_ratio: yes # Require 1:1 images.
  fanarttv_key: "${FANARTTV_API_KEY}" # Automatically replaced by envsubstr since Beets doesn't support this.
  lastfm_key: "${LASTFM_API_KEY}" # Automatically replaced by envsubstr since Beets doesn't support this.
  maxwidth: 1500 # Max width of 1500.
  minwidth: 500 # Require album art to be 500x500 or larger.
  sources: [itunes, fanarttv, lastfm, filesystem] # Sources to enable.

# Acoustic fingerprinting configuration.
chroma:
  auto: yes # Automatically fingerprint and match unrecognized files.

# Feature in Title configuration.
# This is usually frowned upon but I find players don't handle multi artist tags well.
ftintitle:
  auto: yes # Automatically move featured artists to the title.
  drop: no # Do not drop them entirely.
  format: (feat. {0}) # The format appended to the track title.

# Last.fm genre configuration.
lastgenre:
  auto: yes # Automatically fetch genre data from Last.fm.
  separator: "; "
  count: 1 # Fetch the most popular genres.
  force: yes # Force setting the genre tags.
  keep_existing: no # Do not keep pre-existing genre tags.
  prefer_specific: true # Prefer setting specific tags (i.e Grunge instead of Rock) as the primary tag.
  source: album # Source the genre from the album.

# Lyrics configuration.
lyrics:
  auto: yes # Automatically fetch lyrics.
  fallback: "" # Wipe existing lyrics if none are found.
  genius_api_key: "${GENIUS_API_KEY}" # Automatically replaced by envsubstr since Beets doesn't support this.
  sources: [lrclib, genius] # Sources to enable.
  synced: yes # Prefer synced lyrics.

# ReplayGain configuration.
replaygain:
  auto: yes # Automatically analyze and write tags during import.
  backend: ffmpeg # Use ffmpeg.
  overwrite: yes # Overwrite existing replaygain data.

# Tag scrubbing configuration.
scrub:
  auto: yes # Automatically scrub existing tags.
zero:
  fields: images comments encoder # Scrub useless stuff.
  update_database: true # Update the database when finished.
